reporting functions
ehanson8/archivesspace-api pull request #53
Opened 2019-11-04 22:03 UTC by ehanson8

#### What does this PR do?
This PR adds functionality for a time-sensitive report request from DDC but it is what I'm planning to use for future reports so I'd like to do this intelligently. The largest function (which may need to be broken up) extracts fields based on the type of value and calls other new functions for those value types:

- note fields that have a particular structure
- fields where the value is a JSON object with particular fields that need to be consistently extracted (as specified in the obj_field_dict variable)
- fields with a just a simple value

Corresponding tests are included.

#### Includes new or updated dependencies?
NO

2019-11-05 20:21 UTC, gravesm requested changes
If my suggested changes to the `concat_id` function won't work feel free to ignore.

2019-11-05 20:21 UTC, gravesm commented on asaps/models.py
> +def concat_id(rec_obj):
I'm not sure exactly what the requirements are, based on what the data might look like, but it seems to me that this function could be much more succinctly replaced with the following:
```python
ids = [rec_obj.get(f'id_{x}', '') for x in range(4)]
return '-'.join(filter(None, ids))
```

2019-11-05 20:21 UTC, gravesm commented on asaps/models.py
> +        for object in object_list:
`object` is a builtin keyword. I'd suggest using something like `obj` or just `o` in this case.

2019-11-05 20:21 UTC, gravesm commented on asaps/models.py
> +    def extract_fields(self, repo_id, rec_type, field):
This function and the other two should be moved out of this class and into the module level scope as they are really application functionality rather than client functionality. In the case of this function, `self` can just be replaced by a configured client.

2019-11-05 21:36 UTC, ehanson8 commented on asaps/models.py
> +def concat_id(rec_obj):
This worked perfectly, great solution, thanks!

2019-11-06 14:21 UTC, ehanson8 commented
This ended up coming together quickly. I already ran the report for DDC and this change is incomplete until I shift the logging over to cli.py which I plan to do in a separate PR soon. But let me know if this looks correct at the moment

2019-11-06 15:23 UTC, gravesm commented
Yeah, this is looking good!

2019-11-06 15:37 UTC, gravesm approved these changes

2019-11-06 15:38 UTC, merged