update newarchobjs
ehanson8/archivesspace-api pull request #69
Opened 2020-05-11 14:44 UTC by ehanson8

#### What does this PR do?
Refactoring the newarchobjs command established in #65. Changes include:

- Adds function to use an agent CSV that maps a string found in the metadata CSV to a corresponding AS agent URI
- Adds additional date properties to functions for creating agents and archival objects
- Adds functionality to include a second top container for an archival object
- Adds corresponding test for the new function and updates existing tests to account for the new elements

#### Includes new or updated dependencies?
NO

2020-05-11 15:11 UTC, gravesm requested changes

2020-05-11 15:11 UTC, gravesm commented on asaps/cli.py
> +            for author in ast.literal_eval(row['authors']):
As discussed, use `json.loads` here.

2020-05-11 16:09 UTC, ehanson8 commented
Updates made

2020-05-14 14:25 UTC, gravesm approved these changes

2020-05-14 14:27 UTC, merged